import{access,readFile,readdir,stat}from'node:fs/promises';import{join}from'node:path';
const required=['index.html','privacy/index.html','404.html','robots.txt','sitemap.xml','styles.css','multi.css','runtime-config.js','js/app.js','js/data.js','js/extra-data.js','js/traits.js','js/scoring.js','assets/icon.svg','assets/social-card.svg','site.webmanifest'];await Promise.all(required.map(f=>access(join('dist',f))));
async function filesIn(d){const out=[];for(const e of await readdir(d,{withFileTypes:true})){const p=join(d,e.name);e.isDirectory()?out.push(...await filesIn(p)):out.push(p)}return out}
for(const p of await filesIn('src')){const c=await readFile(p,'utf8').catch(()=>null);if(c?.includes('{{CURRENT_YEAR}}'))throw new Error(`Current-year placeholder in ${p}`)}
for(const f of required.filter(f=>/\.(html|txt|xml|js)$/.test(f))){const c=await readFile(join('dist',f),'utf8');if(/{{[^{}]+}}/.test(c))throw new Error(`Unresolved token in ${f}`)}
const html=await readFile('dist/index.html','utf8');for(const[x,re]of[['title',/<title>/],['description',/meta name="description"/],['canonical',/rel="canonical"/],['Open Graph',/property="og:title"/],['Twitter',/name="twitter:card"/],['structured data',/application\/ld\+json/],['main heading',/<h1/],['privacy',/href="\/privacy\/"/]])if(!re.test(html))throw new Error(`Missing ${x}`);
const app=await readFile('dist/js/app.js','utf8');if(/\.innerHTML\s*=|insertAdjacentHTML|localStorage|sessionStorage|document\.cookie|Math\.random|geolocation/.test(app))throw new Error('Unsafe, persistent, location or non-deterministic code found');if(/fetch\(|XMLHttpRequest|WebSocket/.test(app))throw new Error('Unexpected runtime network capability');
const runtimeFiles=(await filesIn('dist')).filter(p=>/\.(html|js|css)$/.test(p)&&!p.endsWith('js/data.js')&&!p.endsWith('js/extra-data.js'));const all=(await Promise.all(runtimeFiles.map(p=>readFile(p,'utf8')))).join('\n');const siteOrigin=new URL(JSON.parse(await readFile('site.config.json','utf8')).siteUrl).origin;for(const match of all.matchAll(/https?:\/\/[^\s"'<>`]+/g)){const url=new URL(match[0]);if(url.origin!==siteOrigin&&url.origin!=='https://schema.org'&&url.hostname!=='localhost'&&url.hostname!=='127.0.0.1')throw new Error('Unexpected external runtime URL')}
const css=await readFile('dist/styles.css','utf8');for(const t of['@media(max-width:340px)','prefers-reduced-motion','focus-visible'])if(!css.includes(t))throw new Error(`Missing CSS requirement: ${t}`);const social=await readFile('dist/assets/social-card.svg','utf8');if(!/width="1200" height="630"/.test(social))throw new Error('Bad social image size');let size=0;for(const p of await filesIn('dist'))size+=(await stat(p)).size;console.log(`Build checks passed. Dist size: ${(size/1024).toFixed(1)} KiB.`);
