import'./year.js';import{celebrities}from'./celebrities.js';import{ageOn,milestoneYears,nextBirthday,parseDate,timeShock}from'./age.js';import{normalize,pickSurprise,searchPeople}from'./search.js';import{initIntegrations}from'./integrations.js';
const $=s=>document.querySelector(s),input=$('#person-search'),list=$('#suggestions'),result=$('#result'),discovery=$('#discovery'),status=$('#status');let matches=[],active=-1,current=null;
const byId=new Map(celebrities.map(x=>[x.id,x]));const featured=['michael-jordan','serena-williams','jim-carrey','snoop-dogg','pewdiepie','george-clooney'].map(x=>byId.get(x)).filter(Boolean);
function renderList(){list.replaceChildren();matches.forEach((person,i)=>{const li=document.createElement('li'),button=document.createElement('button');li.id=`option-${i}`;li.role='option';li.setAttribute('aria-selected',String(i===active));button.type='button';button.textContent=person.name;button.addEventListener('mousedown',e=>e.preventDefault());button.addEventListener('click',()=>select(person));li.append(button);list.append(li)});list.hidden=!matches.length;input.setAttribute('aria-expanded',String(matches.length>0));input.setAttribute('aria-activedescendant',active>=0?`option-${active}`:'')}
function updateSearch(){matches=searchPeople(celebrities,input.value);active=matches.length?0:-1;renderList();$('#no-results').hidden=!input.value.trim()||matches.length>0}
function formatBirth(value){const{year,month,day}=parseDate(value);return new Intl.DateTimeFormat(undefined,{year:'numeric',month:'long',day:'numeric'}).format(new Date(year,month-1,day))}
function setText(selector,text){$(selector).textContent=text}
function select(person,{history=true}={}){current=person;const age=ageOn(person.birthDate),next=nextBirthday(person.birthDate);setText('#result-name',person.name);setText('#age',age);setText('#born',`BORN ${formatBirth(person.birthDate)}`);setText('#profession',`${person.knownFor.toUpperCase()} · VERIFIED LOCAL RECORD`);setText('#next-birthday',next.days===0?`TURNS ${next.turning} TODAY.`:`TURNS ${next.turning} IN ${next.days} DAY${next.days===1?'':'S'}.`);setText('#shock',timeShock(person.birthDate,age));const milestones=$('#milestones');milestones.replaceChildren();for(const mark of milestoneYears(person.birthDate,age)){const li=document.createElement('li'),label=document.createElement('span'),year=document.createElement('strong');label.textContent=`${mark.past?'TURNED':'TURNS'} ${mark.age}`;year.textContent=mark.year;li.append(label,year);milestones.append(li)}result.hidden=false;discovery.hidden=true;input.value=person.name;matches=[];active=-1;renderList();status.textContent=`${person.name} is ${age} years old.`;document.title=`${person.name} is ${age} — Wait, They're HOW Old?`;if(history){const url=new URL(location.href);url.searchParams.set('person',person.id);historyPush(url)}result.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})}
const historyPush=url=>window.history.pushState({person:current?.id},'',url);
input.addEventListener('input',updateSearch);input.addEventListener('keydown',event=>{if(event.key==='ArrowDown'&&matches.length){event.preventDefault();active=(active+1)%matches.length;renderList()}else if(event.key==='ArrowUp'&&matches.length){event.preventDefault();active=(active-1+matches.length)%matches.length;renderList()}else if(event.key==='Enter'&&active>=0){event.preventDefault();select(matches[active])}else if(event.key==='Escape'){matches=[];active=-1;renderList()}});
$('#surprise').addEventListener('click',()=>select(pickSurprise(celebrities,current?.id)));$('#share').addEventListener('click',async()=>{if(!current)return;const age=ageOn(current.birthDate),url=location.href,text=`Wait. ${current.name} is ${age}?! Apparently time is fake.`;try{if(navigator.share)await navigator.share({title:'Wait, They’re HOW Old?',text,url});else{await navigator.clipboard.writeText(`${text} ${url}`);setText('#share-note','LINK COPIED. CRISIS SHARED.')}}catch(error){if(error.name!=='AbortError')setText('#share-note','COPY THE URL FROM YOUR ADDRESS BAR.')}});
for(const person of featured){const b=document.createElement('button');b.type='button';b.textContent=person.name;b.addEventListener('click',()=>select(person));$('#featured').append(b)}
addEventListener('popstate',()=>{const p=byId.get(new URLSearchParams(location.search).get('person'));if(p)select(p,{history:false});else{result.hidden=true;discovery.hidden=false;input.value='';document.title="Wait, They're HOW Old? — Famous Ages & Birthdays"}});const initial=byId.get(new URLSearchParams(location.search).get('person'));if(initial)select(initial,{history:false});initIntegrations();
